"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { ArrowUpRight, ChevronDown, Menu, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { navItems } from "@/lib/freco-content";

export function Wordmark({ inverted = false }: { inverted?: boolean }) {
  return <Link href="/" className={`group inline-flex items-center gap-3 ${inverted ? "text-white" : "text-foreground"}`}><span className="grid size-9 place-items-center rounded-full border border-current/30 text-[10px] font-semibold tracking-[0.2em] transition-transform duration-300 group-hover:rotate-12">FA</span><span className="leading-none"><span className="block text-[15px] font-semibold tracking-[0.22em]">FRECO ART</span><span className="mt-1 block text-[9px] tracking-[0.45em] opacity-60">LTD</span></span></Link>;
}

export function SiteHeader() {
  const [open, setOpen] = useState(false);
  return <header className="absolute inset-x-0 top-0 z-40 text-white"><div className="mx-auto flex w-full max-w-[1440px] items-center justify-between px-6 py-6 lg:px-12"><Wordmark inverted /><nav className="hidden items-center gap-8 lg:flex">{navItems.map((item) => <Link key={item.href} href={item.href} className="nav-link text-[11px] font-medium uppercase tracking-[0.18em] text-white/75 hover:text-white">{item.label}</Link>)}</nav><div className="hidden lg:block"><Button render={<Link href="/landowners" />} className="h-11 rounded-full bg-white px-5 text-[11px] font-semibold uppercase tracking-[0.16em] text-primary hover:bg-white/90">Partner with us <ArrowUpRight size={15} /></Button></div><Button variant="ghost" size="icon" className="text-white hover:bg-white/10 hover:text-white lg:hidden" onClick={() => setOpen(true)} aria-label="Open menu"><Menu size={22} /></Button></div>{open ? <div className="fixed inset-0 flex min-h-dvh flex-col bg-primary px-6 py-6 text-white lg:hidden"><div className="flex items-center justify-between"><Wordmark inverted /><Button variant="ghost" size="icon" className="text-white hover:bg-white/10 hover:text-white" onClick={() => setOpen(false)} aria-label="Close menu"><X size={22} /></Button></div><nav className="mt-20 flex flex-col gap-6">{navItems.map((item) => <Link key={item.href} href={item.href} onClick={() => setOpen(false)} className="text-3xl font-medium tracking-[-0.04em] text-white/90 hover:text-white">{item.label}</Link>)}</nav><div className="mt-auto pb-6"><Button render={<Link href="/landowners" onClick={() => setOpen(false)} />} className="h-12 w-full rounded-full bg-white text-[11px] font-semibold uppercase tracking-[0.16em] text-primary hover:bg-white/90">Partner with us <ArrowUpRight size={15} /></Button></div></div> : null}</header>;
}

export function SiteFooter() {
  return <footer className="bg-ink text-white"><div className="mx-auto max-w-[1440px] px-6 py-16 lg:px-12 lg:py-24"><div className="grid gap-12 lg:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><Wordmark inverted /><p className="mt-8 max-w-sm text-3xl font-medium leading-[1.05] tracking-[-0.04em] text-white/90 lg:text-5xl">Turning land into opportunity.</p><p className="mt-6 max-w-xs text-sm leading-6 text-white/55">Strategic property development, landowner partnerships and purposeful real estate in Kenya.</p></div><FooterColumn title="Company" links={[["About", "/about"], ["Developments", "/developments"], ["Insights", "/insights"], ["Contact", "/contact"]]} /><FooterColumn title="Partnerships" links={[["Landowners", "/landowners"], ["Investors", "/investors"], ["Strategic partners", "/contact"]]} /><div><p className="eyebrow text-white/45">Contact</p><div className="mt-6 space-y-3 text-sm leading-6 text-white/70"><p>[PHONE NUMBER]</p><p>[EMAIL ADDRESS]</p><p>[OFFICE LOCATION]</p><p>[SOCIAL MEDIA]</p></div></div></div><div className="mt-16 flex flex-col gap-4 border-t border-white/15 pt-6 text-[10px] uppercase tracking-[0.16em] text-white/45 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 FRECO ART LTD. ALL RIGHTS RESERVED.</p><div className="flex gap-5"><Link href="/contact">Privacy policy</Link><Link href="/contact">Terms</Link></div></div></div></footer>;
}

function FooterColumn({ title, links }: { title: string; links: string[][] }) { return <div><p className="eyebrow text-white/45">{title}</p><div className="mt-6 flex flex-col gap-3 text-sm text-white/70">{links.map(([label, href]) => <Link key={label} href={href} className="transition-colors hover:text-white">{label}</Link>)}</div></div>; }

export function PageIntro({ eyebrow, title, copy, image = "/freco-hero.webp" }: { eyebrow: string; title: string; copy: string; image?: string }) { return <section className="page-intro relative overflow-hidden bg-ink text-white"><div className="page-intro-image absolute inset-0"><Image src={image} alt="" fill priority className="object-cover opacity-45" sizes="100vw" /></div><div className="page-intro-wash absolute inset-0 bg-gradient-to-r from-ink via-ink/80 to-ink/20" /><div className="page-intro-rule absolute bottom-0 left-6 top-28 w-px bg-white/20 lg:left-12" /><div className="relative mx-auto flex min-h-[590px] max-w-[1440px] items-end px-6 pb-20 pt-40 lg:px-12 lg:pb-28"><div className="max-w-4xl"><p className="eyebrow page-intro-eyebrow text-white/60">{eyebrow}</p><h1 className="page-intro-title mt-6 max-w-4xl text-5xl font-semibold leading-[0.98] tracking-[-0.07em] sm:text-7xl lg:text-[7.6rem]"><span>{title}</span></h1><p className="page-intro-copy mt-8 max-w-2xl text-base leading-7 text-white/70 lg:text-lg">{copy}</p></div></div></section>; }

export function SectionHeading({ eyebrow, title, copy, dark = false }: { eyebrow: string; title: string; copy?: string; dark?: boolean }) { return <div className={dark ? "text-white" : "text-foreground"}><p className={`eyebrow ${dark ? "text-white/45" : "text-primary"}`}>{eyebrow}</p><h2 className="reveal-title mt-5 max-w-3xl text-4xl font-semibold leading-[0.98] tracking-[-0.065em]">{title}</h2>{copy ? <p className={`reveal-copy mt-6 max-w-xl text-base leading-7 ${dark ? "text-white/65" : "text-muted-foreground"}`}>{copy}</p> : null}</div>; }

export function ArrowLink({ href, children, inverted = false }: { href: string; children: React.ReactNode; inverted?: boolean }) { return <Link href={href} className={`inline-flex items-center gap-2 border-b pb-2 text-[11px] font-semibold uppercase tracking-[0.16em] transition-colors ${inverted ? "border-white/40 text-white hover:border-white" : "border-primary/35 text-primary hover:border-primary"}`}>{children}<ArrowUpRight size={15} /></Link>; }

export function ImagePanel({ src, alt, className = "", priority = false }: { src: string; alt: string; className?: string; priority?: boolean }) { return <div className={`relative overflow-hidden bg-muted ${className}`}><Image src={src} alt={alt} fill priority={priority} className="object-cover transition-transform duration-700 ease-out hover:scale-[1.03]" sizes="(max-width: 768px) 100vw, 50vw" /></div>; }

export function Callout({ eyebrow, title, copy, href, label, dark = true }: { eyebrow: string; title: string; copy: string; href: string; label: string; dark?: boolean }) { return <section className={dark ? "bg-primary text-white" : "bg-sand text-foreground"}><div className="mx-auto flex max-w-[1440px] flex-col gap-10 px-6 py-20 lg:flex-row lg:items-end lg:justify-between lg:px-12 lg:py-28"><div className="max-w-3xl"><p className={`eyebrow ${dark ? "text-white/55" : "text-primary"}`}>{eyebrow}</p><h2 className="mt-5 text-4xl font-semibold leading-[0.98] tracking-[-0.065em] sm:text-6xl">{title}</h2><p className={`mt-6 max-w-xl text-base leading-7 ${dark ? "text-white/70" : "text-muted-foreground"}`}>{copy}</p></div><Button render={<Link href={href} />} className={dark ? "h-12 rounded-full bg-white px-6 text-[11px] font-semibold uppercase tracking-[0.16em] text-primary hover:bg-white/90" : "h-12 rounded-full bg-primary px-6 text-[11px] font-semibold uppercase tracking-[0.16em] text-white hover:bg-primary/90"}>{label}<ArrowUpRight size={15} /></Button></div></section>; }

export function FilterPills({ values, active, onChange }: { values: readonly string[]; active: string; onChange: (value: string) => void }) { return <div className="flex flex-wrap gap-2">{values.map((value) => <button key={value} type="button" onClick={() => onChange(value)} className={`rounded-full border px-4 py-2 text-[10px] font-semibold uppercase tracking-[0.14em] transition-colors ${active === value ? "border-primary bg-primary text-white" : "border-border text-muted-foreground hover:border-primary/50 hover:text-primary"}`}>{value}</button>)}</div>; }

export function SelectArrow() { return <ChevronDown size={16} className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-muted-foreground" />; }
