import { ArrowUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { LandSubmissionForm } from "@/components/freco-forms";
import { Callout, PageIntro, SectionHeading, SiteFooter, SiteHeader } from "@/components/freco-site";

export const metadata = { title: "Landowners" };

export default function LandownersPage() {
  return <main><PageIntro eyebrow="For landowners" title="Have land with potential?" copy="Let's explore what it could become." image="/freco-hero.webp" /><SiteHeader /><section className="bg-background"><div className="mx-auto grid max-w-[1440px] gap-14 px-6 py-24 lg:grid-cols-[0.8fr_1.2fr] lg:px-12 lg:py-32"><SectionHeading eyebrow="The opportunity" title="Land is an asset. Development unlocks its potential." copy="Strategic land can become more than an asset sitting idle. It can become homes, apartments, commercial spaces, communities and long-term value." /><div className="space-y-6 text-base leading-7 text-muted-foreground"><p>FRECO ART works with landowners to explore what their land can become, starting with the location, context and opportunity around it.</p><p>There is no one-size-fits-all development answer. We begin with the facts, then look for the direction that makes sense for the place and the people involved.</p><Button render={<a href="#submit-land" />} className="h-12 rounded-full bg-primary px-6 text-[11px] font-semibold uppercase tracking-[0.16em] text-white hover:bg-primary/90">Submit your land <ArrowUpRight size={15} /></Button></div></div></section><section className="bg-sand"><div className="mx-auto max-w-[1440px] px-6 py-24 lg:px-12 lg:py-32"><SectionHeading eyebrow="The process" title="From first conversation to development direction." /><div className="mt-14 grid border-l border-t border-border md:grid-cols-5">{[["01", "Submit", "Tell us about your land."], ["02", "Assess", "We evaluate its strategic potential."], ["03", "Explore", "We investigate viable possibilities."], ["04", "Structure", "We discuss an appropriate partnership."], ["05", "Develop", "We move from opportunity to execution."]].map(([number, title, text]) => <div key={number} className="border-b border-r border-border p-5 lg:p-6"><span className="text-sm text-primary">{number}</span><h3 className="mt-16 text-xl font-semibold tracking-[-0.04em]">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></div></section><section id="submit-land" className="bg-background"><div className="mx-auto grid max-w-[1440px] gap-14 px-6 py-24 lg:grid-cols-[0.75fr_1.25fr] lg:px-12 lg:py-32"><SectionHeading eyebrow="Submit your land" title="Start with the opportunity in front of you." copy="This form is a local-first enquiry flow for now. It is ready to connect to your preferred CRM or email process when you are ready." /><LandSubmissionForm /></div></section><Callout eyebrow="Still exploring?" title="Understand the thinking behind the work." copy="Read how we think about land, development and long-term value." href="/insights" label="Explore insights" /><SiteFooter /></main>;
}
